### ISSUE TITLE
Problem with "extract_log_lik" in rstan 2.9.0/loo 0.1.5

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jgabry/loo#29] opened 2016-03-07 18:02 UTC
I wanted to explore loo. I loaded some previously fit models, and tried :
```
> class(Duree.Incr)
[1] "stanfit"
attr(,"package")
[1] "rstan"
> foo <- extract_log_lik(Duree.Incr)
Error in extract_log_lik(Duree.Incr) : Please load the 'rstan' package.
```
However :
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=fr_FR.utf8       LC_NUMERIC=C            
 [3] LC_TIME=fr_FR.utf8        LC_COLLATE=fr_FR.utf8   
 [5] LC_MONETARY=fr_FR.utf8    LC_MESSAGES=fr_FR.utf8  
 [7] LC_PAPER=fr_FR.utf8       LC_NAME=C               
 [9] LC_ADDRESS=C              LC_TELEPHONE=C          
[11] LC_MEASUREMENT=fr_FR.utf8 LC_IDENTIFICATION=C     

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
[1] loo_0.1.5     rstan_2.9.0-3 ggplot2_2.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3        matrixStats_0.50.1 lattice_0.20-33    MASS_7.3-45      
 [5] brms_0.8.0.9000    grid_3.2.3         plyr_1.8.3         nlme_3.1-125     
 [9] gtable_0.2.0       stats4_3.2.3       coda_0.18-1        scales_0.4.0     
[13] minqa_1.2.4        nloptr_1.0.4       Matrix_1.2-4       splines_3.2.3    
[17] statmod_1.4.24     lme4_1.1-11        tools_3.2.3        munsell_0.4.3    
[21] abind_1.4-3        parallel_3.2.3     compiler_3.2.3     inline_0.3.14    
[25] colorspace_1.2-6   gridExtra_2.2.1  
```
What happens ?

**Comment by jgabry** [comment] 2016-03-07 18:11
I'm pretty sure `extract_log_lik` is giving you the wrong error message (I think this has been fixed on the develop branch). 

Does your model have the log-likelihood stored as a generated quantity (or transformed parameter)? If it doesn't then `extract_log_lik` should be throwing an error (just not the error you got, hence my comment above). If it does have the log-likelihood stored but not using the name `"log_lik"` then it should also throw an error unless you tell `extract_log_lik` what the correct name for the log-likelihood is in your model (which you can do using the second argument to `extract_log_lik`).

**Comment by EmmanuelCharpentier** [comment] 2016-03-07 18:27
``` foo <- extract_log_lik(Duree.Incr)``` fails as already seen. Since this is a stan_generated model, where the log_likelihood (minus some constants) is called "lp__", I try 
```
> foo <- extract_log_lik(Duree.Incr,"lp__")
```
which seems to succeed. But
```
> dim(foo)
[1] 4000    1
```
This merges the separate chains ; therefore
```
> loo(foo)
Computed from 4000 by 1 log-likelihood matrix

         Estimate SE
elpd_loo     81.4 NA
p_loo       344.8 NA
looic      -162.8 NA
Warning messages:
1: 1 (100.0%) Pareto k estimates greater than 1 
2: See PSIS-LOO description (?'loo-package') for more information 
```
loses the SD estimation (and is probably nonsense : why ?). However : 
```
> foo <- extract(Duree.Incr,"lp__",permuted=FALSE,inc_warmup=FALSE)[,,1]
> dim(foo)
[1] 1000    4
> loo(foo)
Computed from 1000 by 4 log-likelihood matrix

         Estimate    SE
elpd_loo    422.5  68.6
p_loo       986.0  80.5
looic      -845.0 137.2
Warning messages:
1: 4 (100.0%) Pareto k estimates greater than 1 
2: See PSIS-LOO description (?'loo-package') for more information
```

Seems to do something reasonable.  The "Pareto k" warnings are another matter, which I'll explore differently.

Is that what you expected ?

**Comment by jgabry** [comment] 2016-03-07 18:37
Oh, I think I see the confusion. For LOO/WAIC you need the _pointwise_ log-likelihood, not `lp__`. For example, for a linear regression model the pointwise log-likelihood can be computed and stored as a generated quantity:

```{stan}
vector[N] log_lik;
for (n in 1:N) log_lik[n] <- normal_log(y[n], mu, sigma); 
```

Stan does not automatically do this for you (there's no way for it to automatically do it for you).  Using `lp__` is essentially like using the sum of the log-likelihood values computed above, but we need each point and not the sum. The code above will result in a log-likelihood vector of length `N` being computed for each posterior draw. If you have `S` posterior draws, then you'll have an `S` by `N` pointwise log-likelihood matrix that you can pass to `loo`.

**Comment by jgabry** [comment] 2016-03-07 18:41
Also see the Details section in `help("extract_log_lik", package = "loo")`, which essentially describes the same thing as in my previous comment but perhaps a bit clearer.

**Comment by EmmanuelCharpentier** [comment] 2016-03-07 18:50
You're right. I (partially) saw my thinko (see edited answer above).

Now, since there is (currently) no way to save quantities generated in the "model" section, I have to compute the log_likelihood *twice*, If I follow you. Or make it a transformed parameter and leave the "model" section about empty (i. e. containing just the priors for parameters and random effects...).

My only defence : I'm working since 6 AM (on a different problem) and it's now about 8 PM...

**Comment by jgabry** [comment] 2016-03-07 19:22
On Mon, Mar 7, 2016 at 1:50 PM, EmmanuelCharpentier <
notifications@github.com> wrote:

> Now, since there is (currently) no way to save quantities generated in the
> "model" section, I have to compute the log_likelihood *twice*, If I
> follow you.
>
Depending on the particular model it might make sense to write out the
log-likelihood twice (once in the model block and once generated quantities
block) because often you can vectorized it in the model block but you'll
still need the non-vectorized version in generated quantities. If you're
not vectorizing it in the model block then you could define a function in
the functions block that computes the log-likelihood and then use that
function in both the model and generated quantities blocks to avoid writing
out the code twice.

> Or make it a transformed parameter and leave the "model" section about
> empty (i. e. containing just the priors for parameters and random
> effects...).
>
That's also ok. If you do compute the pointwise log-likelihood in
transformed parameters you just need to remember to call increment_log_prob
in the model block.

> My only defence : I'm working since 6 AM (on a different problem) and it's
> now about 8 PM...
>
A pretty good defense!

**Comment by jgabry** [comment] 2016-03-08 20:51
I think this is resolved so I'm going to close it, but definitely feel free to ask more questions if you run into any trouble with loo.

**Closed by jgabry** 2016-03-08 20:51 UTC
